<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-09-13T03:19:41+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'Ll Multimodal Transportation',
    'version_installed' => '5.7.5.9',
    'misc' => array(
        'access_entity_updated' => 1472097059,
        'latest_version' => '5.7.5.8',
        'do_page_reindex_check' => false,
    ),
    'cache' => array(
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'custom',
        'full_page_lifetime_value' => '2',
    ),
    'theme' => array(
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => true,
    ),
);
