<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-08-25T05:50:59+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.access_entity_updated
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'Ll Multimodal Transportation',
    'version_installed' => '5.7.5.9',
    'misc' => array(
        'access_entity_updated' => 1472097059,
    ),
);
